DROP TABLE IF EXISTS PLAYERS;

-- Create a table from the csv
-- CREATE TABLE PLAYERS AS SELECT * FROM CSVREAD('Player.csv');

CREATE TABLE PLAYERS AS
SELECT
    PLAYERID,
    CAST(BIRTHYEAR AS INT) AS BIRTHYEAR,
    CAST(BIRTHMONTH AS INT) AS BIRTHMONTH,
    CAST(BIRTHDAY AS INT) AS BIRTHDAY,
    BIRTHCOUNTRY,
    BIRTHSTATE,
    BIRTHCITY,
    CAST(DEATHYEAR AS INT) AS DEATHYEAR,
    CAST(DEATHMONTH AS INT) AS DEATHMONTH,
    CAST(DEATHDAY AS INT) AS DEATHDAY,
    DEATHCOUNTRY,
    DEATHSTATE,
    DEATHCITY,
    NAMEFIRST,
    NAMELAST,
    NAMEGIVEN,
    CAST(WEIGHT AS INT) AS WEIGHT,
    CAST(HEIGHT AS INT) AS HEIGHT,
    BATS,
    THROWS,
    -- Convert strings like '1999-08-23' to DATE
    PARSEDATETIME(DEBUT, 'yyyy-MM-dd') AS DEBUT,
    PARSEDATETIME(FINALGAME, 'yyyy-MM-dd') AS FINALGAME,
    RETROID,
    BBREFID
FROM CSVREAD('Player.csv');

